

-- BEGIN
--     FOR c IN (SELECT table_name FROM user_tables) LOOP
--         EXECUTE IMMEDIATE 'DROP TABLE "' || c.table_name || '" CASCADE CONSTRAINTS';
--     END LOOP;
-- END;

-- PURGE RECYCLEBIN;

CREATE TABLE movie (
    imdb_title_id VARCHAR2(20) PRIMARY KEY,
    title_name VARCHAR2(255),
    duration NUMBER,
    budget NUMBER,
    worldwide_gross_income NUMBER
);


CREATE TABLE director (
    director_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name VARCHAR2(255)
);


CREATE TABLE movie_director (
    imdb_title_id VARCHAR2(20),
    director_id NUMBER,
    PRIMARY KEY (imdb_title_id, director_id),
    CONSTRAINT fk_movie FOREIGN KEY (imdb_title_id) REFERENCES movie(imdb_title_id),
    CONSTRAINT fk_director FOREIGN KEY (director_id) REFERENCES director(director_id)
);

CREATE TABLE vote_rating (
    imdb_title_id VARCHAR2(20) PRIMARY KEY,
    weighted_average_vote NUMBER,
    total_votes NUMBER,
    mean_vote NUMBER,
    median_vote NUMBER,
    CONSTRAINT fk_vote_movie FOREIGN KEY (imdb_title_id) REFERENCES movie(imdb_title_id)
);

CREATE TABLE release_country (
    release_id NUMBER GENERATED AS IDENTITY,
    imdb_title_id VARCHAR2(20),
    country VARCHAR2(255),
    PRIMARY KEY (release_id, imdb_title_id),
    CONSTRAINT fk_country_movie FOREIGN KEY (imdb_title_id) REFERENCES movie(imdb_title_id)
);

CREATE TABLE release_date (
    imdb_title_id VARCHAR2(20) PRIMARY KEY,
    date_published DATE,
    CONSTRAINT fk_date_movie FOREIGN KEY (imdb_title_id) REFERENCES movie(imdb_title_id)
);